[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "functions"
  included_files = ["node_modules/**"]
  external_node_modules = ["@sparticuz/chromium", "puppeteer-core"]
  [functions.timeout]