name: Deploy to Render
on:
  workflow_dispatch:

jobs:
  build:
    name: Build Project
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker Image
        run: docker build -t nat95aws1/cvon:latest .

      - name: Publish Image to Docker Hub
        run: docker push nat95aws1/cvon:latest

  deploy:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    steps:
      - uses: JorgeLNJunior/render-deploy@v1.4.5
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          clear_cache: true # Optional: Clear Render's build cache
          wait_deploy: true
          github_deployment: true
          deployment_environment: "production"
          github_token: ${{ secrets.GITHUB_TOKEN }}
