name: Deploy to EC2
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker Image
        run: docker build -t nat95aws1/cvon:latest .

      - name: Publish Image to Docker Hub
        run: docker push nat95aws1/cvon:latest

  deploy:
    needs: build
    name: Deploy to EC2
    runs-on: aws-ec2
    steps:
      - name: Pull Image from Docker Hub
        run: docker pull nat95aws1/cvon:latest

      - name: Delete Outdated Container
        run: docker rm -f cvonContainer

      - name: Run Container
        run: docker run -d -p 80:3000 --name cvonContainer nat95aws1/cvon
