name: Deploy to Render
on:
  workflow_dispatch:

jobs:
  build:
    name: Build Project
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker Image
        run: docker build -t nat95aws1/cvon:latest .

      - name: Publish Image to Docker Hub
        run: docker push nat95aws1/cvon:latest

  deploy:
    needs: build
    name: Deploy to Render
    runs-on: ubuntu-latest
    steps:
      - name: Trigger redeploy on Render
        run: |
          curl -X POST https://api.render.com/deploy/srv-cvr8uoi4d50c738g34a0 \
            -H 'Authorization: Bearer ${{ secrets.RENDER_API_KEY }}'
